### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by thomasaarholt** [V-Hill/delaunay-triangulation#1]
Hi!
I'm really interested in a faster Delaunay Triangulation solution than the [one in SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html). Have you performed any benchmarking?

My interest lies specifically in performing interpolation on unordered point cloud data (~10 M datapoints, many times), where some triangulation is a necessary precursor.

**Comment by v-hill** [comment]
Hi there,

I've performed some benchmarking and added the single-core results to the readme. The SciPy implemenation is around 40x faster for any given number of points, scaling with the same O(*n* log *n*) running time. This is likely because the SciPy version is written in C and compiled instead of interpreted. My code however, can be run on multiple cores. But you'd need a 40+ core machine to outperform the SciPy algorithm. Hopefully this gives you some insight.
